### ISSUE TITLE
Pattern identifiers

### ISSUE THREAD

**Issue by ncarboni** [swiss-art-research-net/reference-data-models#17]
# Pattern identifiers

Patterns should be uniquely identified by an identifier. 
Patterns reused across several entities have the same identifier.
Patterns identifiers should be unique
Patterns identifiers should encompass basic version information (e.g. 1,2,3).
Pattern identifiers should not contain the following character:
	- spaces (bad practice and not compatible with easyDB? and metaphacts)
	- square brackets (not compatible with easyDB and metaphacts)
	- dots (not compatible with easyDB)

### Proposition 1

Identifiers of 8 characters generated on openrefine with the python uuid library: 
```
import uuid; return str(uuid.uuid4())[:8];
```

result (with the addition of versioning "_1"): 00248d43_1

### Proposition 2

Identifiers of 5 characters, automatically generated based on a formula, which use an incrementor in airtable.

result (with the addition of versioning "_1"): AA950_1

### 1 
use of semantic element in the identifier:

**Q**: should it be possible to add semantic element such as 00248d43_1_appellation?
**A**: the use of semantic element link the identifier to the title of the pattern, which can be changed over time. Same should be said for the category (names and classification)
**A**: the use of semantic element make the element extensively long

### 2 
Currently, there is no automatic way to version. However, the feature is [coming](https://community.airtable.com/t/new-beta-scripting-action/31759/5) on airtable

### 3 
With proposition 1 the identifiers needs to be manually calculated for each field

### 4
With proposition 2 contributions cannot follow the same identifier structure, because it would automatically create duplicates

**Comment by ncarboni** [comment]
DECIDED: to be use "fie_n"
To update field accordingly

**Comment by thomashaensli** [comment]
just another thought: 
if we want to reuse it consistently in EasyDB, we should go for "fie_n" (lowercase)
